apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: Jupyter notebook image with TensorFlow libraries
      and dependencies to start experimenting with advanced AI/ML notebooks.
    opendatahub.io/notebook-image-name: '[3.3] Jupyter | TensorFlow | CUDA | Python
      3.12'
    opendatahub.io/notebook-image-order: '14'
    opendatahub.io/notebook-image-url: https://github.com/red-hat-data-services/notebooks/blob/main/jupyter/tensorflow
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    platform.opendatahub.io/type: OpenShift AI Self-Managed
    platform.opendatahub.io/version: 3.3.0
  labels:
    app.kubernetes.io/created-by: byon
    app.kubernetes.io/part-of: workbenches
    app.opendatahub.io/workbenches: 'true'
    component.opendatahub.io/name: notebooks
    opendatahub.io/component: 'true'
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
    platform.opendatahub.io/part-of: workbenches
  name: tensorflow-3.3
  namespace: redhat-ods-applications
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      opendatahub.io/image-tag-outdated: 'true'
      opendatahub.io/notebook-build-commit: 3e71410
      opendatahub.io/notebook-python-dependencies: "[\n  {\"name\":\"TensorFlow\"\
        ,\"version\":\"2.7\"},\n  {\"name\":\"Tensorboard\",\"version\":\"2.6\"},\n\
        \  {\"name\":\"Boto3\",\"version\":\"1.17\"},\n  {\"name\":\"Kafka-Python\"\
        ,\"version\":\"2.0\"},\n  {\"name\":\"Matplotlib\",\"version\":\"3.4\"},\n\
        \  {\"name\":\"Numpy\",\"version\":\"1.19\"},\n  {\"name\":\"Pandas\",\"version\"\
        :\"1.2\"},\n  {\"name\":\"Scikit-learn\",\"version\":\"0.24\"},\n  {\"name\"\
        :\"Scipy\",\"version\":\"1.6\"}\n]\n"
      opendatahub.io/notebook-software: "[\n  {\"name\":\"CUDA\",\"version\":\"11.4\"\
        },\n  {\"name\":\"Python\",\"version\":\"v3.8\"},\n  {\"name\":\"TensorFlow\"\
        ,\"version\":\"2.7\"}\n]\n"
    from:
      kind: DockerImage
      name: quay.io/modh/cuda-notebooks@sha256:6fadedc5a10f5a914bb7b27cd41bc644392e5757ceaf07d930db884112054265
    name: '1.2'
    referencePolicy:
      type: Source
  - annotations:
      opendatahub.io/image-tag-outdated: 'true'
      opendatahub.io/notebook-build-commit: 07015ec
      opendatahub.io/notebook-python-dependencies: "[\n  {\"name\":\"TensorFlow\"\
        ,\"version\":\"2.11\"},\n  {\"name\":\"Tensorboard\",\"version\":\"2.11\"\
        },\n  {\"name\":\"Boto3\",\"version\":\"1.26\"},\n  {\"name\":\"Kafka-Python\"\
        ,\"version\":\"2.0\"},\n  {\"name\":\"Kfp-tekton\",\"version\":\"1.5\"},\n\
        \  {\"name\":\"Matplotlib\",\"version\":\"3.6\"},\n  {\"name\":\"Numpy\",\"\
        version\":\"1.24\"},\n  {\"name\":\"Pandas\",\"version\":\"1.5\"},\n  {\"\
        name\":\"Scikit-learn\",\"version\":\"1.2\"},\n  {\"name\":\"Scipy\",\"version\"\
        :\"1.10\"},\n  {\"name\":\"Elyra\",\"version\":\"3.15\"}\n]\n"
      opendatahub.io/notebook-software: "[\n  {\"name\":\"CUDA\",\"version\":\"11.8\"\
        },\n  {\"name\":\"Python\",\"version\":\"v3.9\"},\n  {\"name\":\"TensorFlow\"\
        ,\"version\":\"2.11\"}\n]\n"
    from:
      kind: DockerImage
      name: quay.io/modh/cuda-notebooks@sha256:88d80821ff8c5d53526794261d519125d0763b621d824f8c3222127dab7b6cc8
    name: '2023.1'
    referencePolicy:
      type: Source
  - annotations:
      opendatahub.io/image-tag-outdated: 'true'
      opendatahub.io/notebook-build-commit: 76a016f
      opendatahub.io/notebook-python-dependencies: "[\n  {\"name\":\"TensorFlow\"\
        ,\"version\":\"2.13\"},\n  {\"name\":\"Tensorboard\",\"version\":\"2.13\"\
        },\n  {\"name\":\"Boto3\",\"version\":\"1.28\"},\n  {\"name\":\"Kafka-Python\"\
        ,\"version\":\"2.0\"},\n  {\"name\":\"Kfp-tekton\",\"version\":\"1.5\"},\n\
        \  {\"name\":\"Matplotlib\",\"version\":\"3.6\"},\n  {\"name\":\"Numpy\",\"\
        version\":\"1.24\"},\n  {\"name\":\"Pandas\",\"version\":\"1.5\"},\n  {\"\
        name\":\"Scikit-learn\",\"version\":\"1.3\"},\n  {\"name\":\"Scipy\",\"version\"\
        :\"1.11\"},\n  {\"name\":\"Elyra\",\"version\":\"3.15\"},\n  {\"name\":\"\
        PyMongo\",\"version\":\"4.5\"},\n  {\"name\":\"Pyodbc\",\"version\":\"4.0\"\
        },\n  {\"name\":\"Codeflare-SDK\",\"version\":\"0.13\"},\n  {\"name\":\"Sklearn-onnx\"\
        ,\"version\":\"1.15\"},\n  {\"name\":\"Psycopg\",\"version\":\"3.1\"},\n \
        \ {\"name\":\"MySQL Connector/Python\",\"version\":\"8.0\"}\n]\n"
      opendatahub.io/notebook-software: "[\n  {\"name\":\"CUDA\",\"version\":\"11.8\"\
        },\n  {\"name\":\"Python\",\"version\":\"v3.9\"},\n  {\"name\":\"TensorFlow\"\
        ,\"version\":\"2.13\"}\n]\n"
    from:
      kind: DockerImage
      name: quay.io/modh/cuda-notebooks@sha256:3da74d732d158b92eaada0a27fb7067fa18c8bde5033c672e23caed0f21d6481
    name: '2023.2'
    referencePolicy:
      type: Source
  - annotations:
      opendatahub.io/image-tag-outdated: 'true'
      opendatahub.io/notebook-build-commit: b42b86c
      opendatahub.io/notebook-python-dependencies: "[\n  {\"name\": \"TensorFlow\"\
        , \"version\": \"2.15\"},\n  {\"name\": \"Tensorboard\", \"version\": \"2.15\"\
        },\n  {\"name\": \"Boto3\", \"version\": \"1.34\"},\n  {\"name\": \"Kafka-Python\"\
        , \"version\": \"2.0\"},\n  {\"name\": \"Kfp\", \"version\": \"2.5\"},\n \
        \ {\"name\": \"Matplotlib\", \"version\": \"3.8\"},\n  {\"name\": \"Numpy\"\
        , \"version\": \"1.26\"},\n  {\"name\": \"Pandas\", \"version\": \"2.2\"},\n\
        \  {\"name\": \"Scikit-learn\", \"version\": \"1.4\"},\n  {\"name\": \"Scipy\"\
        , \"version\": \"1.12\"},\n  {\"name\": \"Odh-Elyra\", \"version\": \"3.16\"\
        },\n  {\"name\": \"PyMongo\", \"version\": \"4.6\"},\n  {\"name\": \"Pyodbc\"\
        , \"version\": \"5.1\"},\n  {\"name\": \"Codeflare-SDK\", \"version\": \"\
        0.21\"},\n  {\"name\": \"Sklearn-onnx\", \"version\": \"1.16\"},\n  {\"name\"\
        : \"Psycopg\", \"version\": \"3.1\"},\n  {\"name\": \"MySQL Connector/Python\"\
        , \"version\": \"8.3\"}\n]\n"
      opendatahub.io/notebook-software: "[\n  {\"name\": \"CUDA\", \"version\": \"\
        12.1\"},\n  {\"name\": \"Python\", \"version\": \"v3.9\"},\n  {\"name\": \"\
        TensorFlow\", \"version\": \"2.15\"}\n]\n"
    from:
      kind: DockerImage
      name: quay.io/modh/cuda-notebooks@sha256:0e57a0b756872636489ccd713dc9f00ad69d0c481a66ee0de97860f13b4fedcd
    name: '2024.1'
    referencePolicy:
      type: Source
  - annotations:
      opendatahub.io/image-tag-outdated: 'true'
      opendatahub.io/notebook-build-commit: be38cca
      opendatahub.io/notebook-python-dependencies: "[\n  {\"name\": \"JupyterLab\"\
        ,\"version\": \"4.2\"},\n  {\"name\": \"TensorFlow\", \"version\": \"2.17\"\
        },\n  {\"name\": \"Tensorboard\", \"version\": \"2.17\"},\n  {\"name\": \"\
        Nvidia-CUDA-CU12-Bundle\", \"version\": \"12.3\"},\n  {\"name\": \"Boto3\"\
        , \"version\": \"1.35\"},\n  {\"name\": \"Kafka-Python-ng\", \"version\":\
        \ \"2.2\"},\n  {\"name\": \"Kfp\", \"version\": \"2.5\"},\n  {\"name\": \"\
        Matplotlib\", \"version\": \"3.9\"},\n  {\"name\": \"Numpy\", \"version\"\
        : \"1.26\"},\n  {\"name\": \"Pandas\", \"version\": \"2.2\"},\n  {\"name\"\
        : \"Scikit-learn\", \"version\": \"1.5\"},\n  {\"name\": \"Scipy\", \"version\"\
        : \"1.14\"},\n  {\"name\": \"Odh-Elyra\", \"version\": \"4.2\"},\n  {\"name\"\
        : \"PyMongo\", \"version\": \"4.8\"},\n  {\"name\": \"Pyodbc\", \"version\"\
        : \"5.1\"},\n  {\"name\": \"Codeflare-SDK\", \"version\": \"0.24\"},\n  {\"\
        name\": \"Sklearn-onnx\", \"version\": \"1.17\"},\n  {\"name\": \"Psycopg\"\
        , \"version\": \"3.2\"},\n  {\"name\": \"MySQL Connector/Python\", \"version\"\
        : \"9.0\"}\n]\n"
      opendatahub.io/notebook-software: "[\n  {\"name\": \"CUDA\", \"version\": \"\
        12.4\"},\n  {\"name\": \"Python\", \"version\": \"v3.11\"},\n  {\"name\":\
        \ \"TensorFlow\", \"version\": \"2.17\"}\n]\n"
    from:
      kind: DockerImage
      name: quay.io/modh/cuda-notebooks@sha256:99d3fb964e635873214de4676c259a96c2ea25f3f79cc4bead5bc9f39aba34c0
    name: '2024.2'
    referencePolicy:
      type: Source
  - annotations:
      opendatahub.io/notebook-build-commit: 8e73cac
      opendatahub.io/notebook-python-dependencies: "[\n  {\"name\": \"JupyterLab\"\
        ,\"version\": \"4.4\"},\n  {\"name\": \"TensorFlow\", \"version\": \"2.18\"\
        },\n  {\"name\": \"Tensorboard\", \"version\": \"2.18\"},\n  {\"name\": \"\
        Nvidia-CUDA-CU12-Bundle\", \"version\": \"12.5\"},\n  {\"name\": \"Boto3\"\
        , \"version\": \"1.37\"},\n  {\"name\": \"Kafka-Python-ng\", \"version\":\
        \ \"2.2\"},\n  {\"name\": \"Kfp\", \"version\": \"2.12\"},\n  {\"name\": \"\
        Matplotlib\", \"version\": \"3.10\"},\n  {\"name\": \"Numpy\", \"version\"\
        : \"1.26\"},\n  {\"name\": \"Pandas\", \"version\": \"2.2\"},\n  {\"name\"\
        : \"Scikit-learn\", \"version\": \"1.6\"},\n  {\"name\": \"Scipy\", \"version\"\
        : \"1.15\"},\n  {\"name\": \"Odh-Elyra\", \"version\": \"4.2\"},\n  {\"name\"\
        : \"PyMongo\", \"version\": \"4.11\"},\n  {\"name\": \"Pyodbc\", \"version\"\
        : \"5.2\"},\n  {\"name\": \"Codeflare-SDK\", \"version\": \"0.30\"},\n  {\"\
        name\": \"Sklearn-onnx\", \"version\": \"1.18\"},\n  {\"name\": \"Psycopg\"\
        , \"version\": \"3.2\"},\n  {\"name\": \"MySQL Connector/Python\", \"version\"\
        : \"9.3\"}\n]\n"
      opendatahub.io/notebook-software: "[\n  {\"name\": \"CUDA\", \"version\": \"\
        12.6\"},\n  {\"name\": \"Python\", \"version\": \"v3.11\"},\n  {\"name\":\
        \ \"TensorFlow\", \"version\": \"2.18\"}\n]\n"
      opendatahub.io/workbench-image-recommended: 'false'
    from:
      kind: DockerImage
      name: registry.redhat.io/rhoai/odh-workbench-jupyter-tensorflow-cuda-py311-rhel9@sha256:a2f863e8df080b683f52453b3a3b8c1f70a50c9bbe9480d7a55da8f0d54fbee2
    name: '2025.1'
    referencePolicy:
      type: Source
  - annotations:
      opendatahub.io/notebook-build-commit: 8e73cac
      opendatahub.io/notebook-python-dependencies: "[\n  {\"name\": \"JupyterLab\"\
        ,\"version\": \"4.4\"},\n  {\"name\": \"TensorFlow\", \"version\": \"2.20\"\
        },\n  {\"name\": \"Tensorboard\", \"version\": \"2.20\"},\n  {\"name\": \"\
        Nvidia-CUDA-CU12-Bundle\", \"version\": \"12.9\"},\n  {\"name\": \"Boto3\"\
        , \"version\": \"1.40\"},\n  {\"name\": \"Kafka-Python-ng\", \"version\":\
        \ \"2.2\"},\n  {\"name\": \"Kfp\", \"version\": \"2.14\"},\n  {\"name\": \"\
        Matplotlib\", \"version\": \"3.10\"},\n  {\"name\": \"Numpy\", \"version\"\
        : \"2.1\"},\n  {\"name\": \"Pandas\", \"version\": \"2.3\"},\n  {\"name\"\
        : \"Scikit-learn\", \"version\": \"1.7\"},\n  {\"name\": \"Scipy\", \"version\"\
        : \"1.16\"},\n  {\"name\": \"Odh-Elyra\", \"version\": \"4.3\"},\n  {\"name\"\
        : \"PyMongo\", \"version\": \"4.15\"},\n  {\"name\": \"Pyodbc\", \"version\"\
        : \"5.2\"},\n  {\"name\": \"Codeflare-SDK\", \"version\": \"0.34\"},\n  {\"\
        name\": \"Feast\", \"version\": \"0.59\"},\n  {\"name\": \"Sklearn-onnx\"\
        , \"version\": \"1.19\"},\n  {\"name\": \"Psycopg\", \"version\": \"3.2\"\
        },\n  {\"name\": \"MySQL Connector/Python\", \"version\": \"9.4\"}\n]\n"
      opendatahub.io/notebook-software: "[\n  {\"name\": \"CUDA\", \"version\": \"\
        12.8\"},\n  {\"name\": \"Python\", \"version\": \"v3.12\"},\n  {\"name\":\
        \ \"TensorFlow\", \"version\": \"2.20\"}\n]\n"
      opendatahub.io/workbench-image-recommended: 'true'
    from:
      kind: DockerImage
      name: registry.redhat.io/rhoai/odh-workbench-jupyter-tensorflow-cuda-py312-rhel9@sha256:8036dd68f3c12b17cd6fe5cd2a37462541328b49e1d8fa086e2c114dc5f2e11c
    name: '2025.2'
    referencePolicy:
      type: Source
